### ISSUE TITLE
fix local provisioning 

### ISSUE THREAD

**Issue by maat-code** [ttssdev/appflow#82]
Edit Makefile to fix appflow local issue

**Comment by 89luca89** [comment]
local provisioning fixed in new appflow python porting.

`appflow.py default "tenant-id" "tenant-name" "environment"`

will create the default ~/appflow/config.yml

`appflow.py init`

will deploy the default assh folders and enable bash completion for shell

`appflow.py ssh`

will deploy the assh configs
